server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
